// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHRFk2fVROcN6bOSp37uosapPJR0z7pGA',
    appId: '1:824431462522:web:a63600e3794479124313c3',
    messagingSenderId: '824431462522',
    projectId: 'pucacess',
    authDomain: 'pucacess.firebaseapp.com',
    storageBucket: 'pucacess.firebasestorage.app',
    measurementId: 'G-J2TH4D5M5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI4prKIJc8wWOizK1SsNbK1LXlTo9M7Jg',
    appId: '1:824431462522:android:d8d490a0d06d4a054313c3',
    messagingSenderId: '824431462522',
    projectId: 'pucacess',
    storageBucket: 'pucacess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3CT_LsfY0qIksfPQ-5mt7FTXfdSn9fo0',
    appId: '1:824431462522:ios:d7e742e6571a34624313c3',
    messagingSenderId: '824431462522',
    projectId: 'pucacess',
    storageBucket: 'pucacess.firebasestorage.app',
    iosBundleId: 'com.pucaccess.pucAccess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3CT_LsfY0qIksfPQ-5mt7FTXfdSn9fo0',
    appId: '1:824431462522:ios:d7e742e6571a34624313c3',
    messagingSenderId: '824431462522',
    projectId: 'pucacess',
    storageBucket: 'pucacess.firebasestorage.app',
    iosBundleId: 'com.pucaccess.pucAccess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHRFk2fVROcN6bOSp37uosapPJR0z7pGA',
    appId: '1:824431462522:web:f1109a96c91a1d764313c3',
    messagingSenderId: '824431462522',
    projectId: 'pucacess',
    authDomain: 'pucacess.firebaseapp.com',
    storageBucket: 'pucacess.firebasestorage.app',
    measurementId: 'G-J1QDC4WETT',
  );
}
